---
- name: Deploy Factorio server
  hosts: localhost
  vars_files:
    - vars/factorio.yml

  roles:
    - server_init

  tasks:
    - name: Refresh Ansible inventory
      ansible.builtin.meta: "refresh_inventory"

- name: Setup Factorio server
  hosts: ansible_managed_vm
  remote_user: root
  vars_files:
    - vars/factorio.yml

  tasks:
    - name: Setup initial server
      ansible.builtin.include_role:
        name: factorio_init
      when: not (hostvars['localhost']['snapshot_exists'] | default(false))

    - name: Start Factorio server
      community.docker.docker_compose_v2:
        project_src: factorio
      when: hostvars['localhost']['snapshot_exists'] | default(false)
