---
- name: Save the game
  hosts: ansible_managed_vm
  remote_user: root
  vars_files:
    - vars/factorio.yml
  roles:
    - factorio_save

- name: Snapshot and delete Factorio server
  hosts: localhost
  vars_files:
    - vars/factorio.yml

  roles:
    - server_snapshot
