---
- name: Save game from Factorio server
  hosts: ansible_managed_vm
  vars_files:
    - vars/factorio.yml
  remote_user: root

  roles:
    - factorio_save

- name: Destroy Factorio server
  hosts: localhost
  vars_files:
    - vars/factorio.yml

  roles:
    - server_destroy
