---
- name: Deploy Factorio server
  hosts: localhost
  vars:
    terraform_directory: "{{ playbook_dir }}/terraform"
  vars_files:
    - vars/factorio.yml

  tasks:
    - name: Deploy server and components
      community.general.terraform:
        project_path: "{{ terraform_directory }}"
        state: present
        force_init: true
        provider_upgrade: true
        variables:
          hcloud_api_token: "{{ lookup('env', 'TF_VAR_hcloud_api_token') }}"
          server_type: "{{ server_type }}"
          datacenter: "{{ datacenter }}"
          image: "{{ image }}"
          pub_ssh_key: "{{ pub_ssh_key }}"
        backend_config:
          address: "{{ tf_address }}"
          lock_address: "{{ tf_lock_address }}"
          unlock_address: "{{ tf_unlock_address }}"
          username: "{{ tf_username }}"
          password: "{{ tf_password }}"
          lock_method: "{{ tf_lock_method }}"
          unlock_method: "{{ tf_unlock_method }}"
          retry_wait_min: "{{ tf_retry_wait_min }}"

    - name: Get the public IP address of Factorio server
      ansible.builtin.command: terraform output -raw ipv4_address
      register: factorio_ip
      args:
        chdir: "{{ terraform_directory }}"
      changed_when: factorio_ip.rc != 0

    - name: Add Factorio server to the inventory
      ansible.builtin.add_host:
        groups: ansible_managed_vm
        name: "{{ factorio_ip.stdout }}"

    - name: Wait for server to come online
      ansible.builtin.wait_for:
        host: "{{ factorio_ip.stdout }}"
        port: 22
        delay: 10

- name: Setup Factorio server
  hosts: ansible_managed_vm
  remote_user: root
  vars_files:
    - /vars/factorio.yml
  roles:
    - factorio_init
