---
- name: Create HCloud Firewall
  hetzner.hcloud.firewall:
    name: factorio-firewall
    state: present
    api_token: "{{ hcloud_api_token }}"
    rules:
      - description: ICMP
        direction: in
        protocol: icmp
        source_ips:
          - 0.0.0.0/0
          - ::/0
      - description: Factorio Server Port
        direction: in
        protocol: udp
        port: 34197
        source_ips:
          - 0.0.0.0/0
          - ::/0
      - description: SSH
        direction: in
        protocol: tcp
        port: 22
        source_ips:
          - 0.0.0.0/0
          - ::/0
  async: 300
  poll: 0
  register: hcloud_firewall

- name: Create HCloud SSH key
  hetzner.hcloud.ssh_key:
    name: factorio-sshkey
    state: present
    api_token: "{{ hcloud_api_token }}"
    public_key: "{{ lookup('ansible.builtin.file', '{{ hcloud_pub_ssh_key }}') }}"
  async: 300
  poll: 0
  register: hcloud_ssh_key

- name: Create HCloud IPv4 address
  hetzner.hcloud.primary_ip:
    name: factorio-ipv4
    state: present
    api_token: "{{ hcloud_api_token }}"
    datacenter: "{{ hcloud_datacenter }}"
    type: ipv4
  async: 300
  poll: 0
  register: hcloud_ipv4

- name: Create HCloud IPv6 address
  hetzner.hcloud.primary_ip:
    name: factorio-ipv6
    state: present
    api_token: "{{ hcloud_api_token }}"
    datacenter: "{{ hcloud_datacenter }}"
    type: ipv6
  async: 300
  poll: 0
  register: hcloud_ipv6

- name: Wait for async tasks to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: hcloud_async
  until: hcloud_async.finished
  retries: 30
  delay: 2
  with_items:
    - "{{ hcloud_firewall }}"
    - "{{ hcloud_ssh_key }}"
    - "{{ hcloud_ipv4 }}"
    - "{{ hcloud_ipv6 }}"

- name: Create HCloud Server
  hetzner.hcloud.server:
    name: factorio
    api_token: "{{ hcloud_api_token }}"
    state: present
    server_type: "{{ hcloud_server_type }}"
    image: "{{ hcloud_image }}"
    location: "{{ hcloud_datacenter }}"
    ipv4: "{{ hcloud_async.results | selectattr('ansible_job_id', 'equalto', hcloud_ipv4.ansible_job_id) | map(attribute='hcloud_primary_ip.id') | first }}"
    ipv6: "{{ hcloud_async.results | selectattr('ansible_job_id', 'equalto', hcloud_ipv6.ansible_job_id) | map(attribute='hcloud_primary_ip.id') | first }}"
    firewalls:
      - "{{ hcloud_async.results | selectattr('ansible_job_id', 'equalto', hcloud_firewall.ansible_job_id) | map(attribute='hcloud_firewall.id') | first }}"
    ssh_keys:
      - "{{ hcloud_async.results | selectattr('ansible_job_id', 'equalto', hcloud_ssh_key.ansible_job_id) | map(attribute='hcloud_ssh_key.id') | first }}"
  register: hcloud_server

- name: Create CloudFlare DNS A record
  community.general.cloudflare_dns:
    zone: "{{ cf_zone }}"
    record: "{{ cf_record }}"
    type: A
    value: "{{ hcloud_async.results | selectattr('ansible_job_id', 'equalto', hcloud_ipv4.ansible_job_id) | map(attribute='hcloud_primary_ip.ip') | first }}"
    api_token: "{{ cf_api_token }}"
    ttl: 120
  when:
    - cf_api_token is defined
    - cf_api_token != ''
    - cf_zone is defined
    - cf_zone != ''
    - cf_record is defined
    - cf_record != ''

- name: Create CloudFlare DNS AAAA record
  community.general.cloudflare_dns:
    zone: "{{ cf_zone }}"
    record: "{{ cf_record }}"
    type: AAAA
    value: "{{ hcloud_async.results | selectattr('ansible_job_id', 'equalto', hcloud_ipv6.ansible_job_id) | map(attribute='hcloud_primary_ip.ip') | first }}"
    api_token: "{{ cf_api_token }}"
    ttl: 120
  when:
    - cf_api_token is defined
    - cf_api_token != ''
    - cf_zone is defined
    - cf_zone != ''
    - cf_record is defined
    - cf_record != ''

- name: Wait for server to come online
  ansible.builtin.wait_for:
    host: "{{ factorio_ipv4.stdout }}"
    port: 22
    delay: 10
