---
- name: Read RCON password
  ansible.builtin.slurp:
    src: /opt/factorio/config/rconpw
  register: rcon_password
  no_log: true

- name: Save the game using RCON
  community.docker.docker_container:
    name: rcon
    image: outdead/rcon
    interactive: true
    network_mode: host
    command: |
      ./rcon -a localhost:27015 -p "{{ rcon_password.content | b64decode | trim }}" "/save ansible_managed_save.zip"
    tty: true
  register: save_file
  no_log: true

- name: Stop Factorio server
  community.docker.docker_compose_v2:
    project_src: factorio
    state: stopped

- name: Download save file
  ansible.builtin.fetch:
    src: /opt/factorio/saves/ansible_managed_save.zip
    dest: "{{ playbook_dir }}/"
    flat: true
